# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128)),
                ('job_desc', models.TextField()),
                ('requirement', models.TextField()),
                ('company', models.CharField(max_length=128)),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
