# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
